---
- name: "Configure prompt for normal users"
  become: true
  loop:
    - /home/service/.bashrc
    - /etc/skel/.bashrc
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    state: present
    regexp: "^PS1="
    line: |
      PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\H\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

- name: "Configure prompt for root user"
  become: true
  ansible.builtin.lineinfile:
    path: "/root/.bashrc"
    state: present
    regexp: "^PS1="
    line: |
      PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\H\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

- name: "Install Bash Completion"
  become: true
  ansible.builtin.apt:
    package: "bash-completion"
    state: "present"

- name: "Install Generic Colouriser"
  become: true
  ansible.builtin.apt:
    package: "grc"
    state: "present"

- name: "Enable Generic Colouriser"
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/default/grc"
    line: "GRC_ALIASES=true"
    regexp: 'GRC_ALIASES=false'
    state: present
