---
- name: "Configure login banner"
  become: true
  ansible.builtin.copy:
    src: "files/etc/issue"
    dest: "/etc/issue"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Configure MOTD banner"
  become: true
  ansible.builtin.copy:
    src: "files/etc/update-motd.d/00-custom-header"
    dest: "/etc/update-motd.d/00-custom-header"
    owner: "root"
    group: "root"
    mode: "0655"
