---
- name: "Enable colored prompt"
  become: true
  loop:
    - /home/service/.bashrc
    - /root/.bashrc
    - /etc/skel/.bashrc
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: "force_color_prompt=yes"
    regexp: '#?force_color_prompt=yes'
    state: present

- name: "Set prompt color to red for root"
  become: true
  ansible.builtin.replace:
    path: "/root/.bashrc"
    regexp: '^(.*PS1=.*)32m(.*)$'
    replace: '\g<1>31m\g<2>'

- name: "Install Generic Colouriser"
  become: true
  ansible.builtin.apt:
    package: "grc"
    state: "present"

- name: "Enable Generic Colouriser"
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/default/grc"
    line: "GRC_ALIASES=true"
    regexp: 'GRC_ALIASES=false'
    state: present
