---
- name: "Configure OpenSSH Server"
  become: true
  ansible.builtin.copy:
    src: "files/etc/ssh/sshd_config"
    dest: "/etc/ssh/sshd_config"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Restart OpenSSH Server"

- name: "Enable OpenSSH Server"
  become: true
  ansible.builtin.service:
    name: "ssh"
    enabled: true

- name: "Configure UFW to allow connections to OpenSSH Server"
  become: true
  community.general.ufw:
    rule: "allow"
    name: "OpenSSH"
